### ISSUE TITLE
캔들관련 기능추가 문의입니다.

### ISSUE THREAD

**Issue by realapril** [brianalabs/crypto-exchange-client#1]
안녕하세요   
현재 라이브러리에서 GetCandleByMinute만 제공하는듯한데    
업비트API 에서 제공하는 day/week/month 단위 캔들은 제공할 계획이 없으신가요?   
포맷이 거의 똑같아서 난이도가 높지 않을것같아서 여쭤봅니다.

**Comment by peterkimzz** [comment]
안녕하세요 @realapril 님

요청 주신 기능에 대한 커밋입니다.

https://github.com/brianalabs/crypto-exchange-client/commit/7e22b6edf3bc4f7ffd0835c2e83e235ba0d04679

`upbit-client@0.4.1` 버전 사용하시면 사용 가능하실거에요.
